// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveBaseRight = NULL;
SpeedController* RobotMap::driveBaseFront = NULL;
SpeedController* RobotMap::driveBaseLeft = NULL;
RobotDrive3* RobotMap::driveBaseDrive3 = NULL;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveBaseFront = new Jaguar(1, 1);
	lw->AddActuator("RobotDrive3", "Front", (Jaguar*) driveBaseFront);
	
	driveBaseLeft = new Jaguar(1, 2);
	lw->AddActuator("RobotDrive3", "Left", (Jaguar*) driveBaseLeft);
	
	driveBaseRight = new Jaguar(1, 3);
	lw->AddActuator("RobotDrive3", "Right", (Jaguar*) driveBaseRight);
	
	driveBaseDrive3 = new RobotDrive3(driveBaseFront, driveBaseLeft,
              driveBaseRight);
	
	driveBaseDrive3->SetSafetyEnabled(true);
        driveBaseDrive3->SetExpiration(0.1);
        driveBaseDrive3->SetSensitivity(0.5);
        driveBaseDrive3->SetMaxOutput(1.0);


	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
